# Generated by Django 4.2.21 on 2025-06-04 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(max_length=500, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('price', models.CharField(choices=[('£', '£'), ('££', '££'), ('£££', '£££'), ('££££', '££££'), ('£££££', '£££££')], default='£')),
                ('food', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No')),
                ('craft_beer', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No')),
                ('beer_garden', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No')),
                ('dog_friendly', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No')),
                ('pool_table', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No')),
                ('dart_board', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No')),
                ('excerpt', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_listing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pubs.pub')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('closed', models.BooleanField(default=False)),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='pubs.pub')),
            ],
            options={
                'unique_together': {('pub', 'day')},
            },
        ),
    ]
