# Generated by Django 4.2.21 on 2025-06-01 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=500, unique=True)),
                ('price', models.CharField(max_length=5, unique=True)),
                ('food', models.BooleanField()),
                ('craft_beer', models.BooleanField()),
                ('beer_garden', models.BooleanField()),
                ('dog_friendly', models.BooleanField()),
                ('pool_table', models.BooleanField()),
                ('dart_board', models.BooleanField()),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_listing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
