# Generated by Django 4.2.21 on 2025-06-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='beer_garden',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='craft_beer',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='dart_board',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='dog_friendly',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pool_table',
        ),
        migrations.AddField(
            model_name='pub',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pub',
            name='food',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='pub',
            name='price',
            field=models.IntegerField(choices=[(0, '£'), (1, '££'), (2, '£££'), (3, '££££'), (4, '£££££')], default=0),
        ),
        migrations.AddField(
            model_name='pub',
            name='beer_Garden',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='pub',
            name='craft_Beer',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='pub',
            name='dart_Board',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='pub',
            name='dog_Friendly',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='pub',
            name='pool_Table',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
