# Generated by Django 4.2.21 on 2025-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
