# Generated by Django 4.2.21 on 2025-06-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0002_pub_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='email',
            field=models.CharField(blank=True),
        ),
    ]
