# Generated by Django 4.2.21 on 2025-06-05 20:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0002_alter_pub_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='pub',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
