# Generated by Django 4.2.21 on 2025-06-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0003_alter_pub_email_alter_pub_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='website',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
