# Generated by Django 4.2.21 on 2025-06-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='pub',
        ),
        migrations.RenameField(
            model_name='pub',
            old_name='beer_Garden',
            new_name='beer_garden',
        ),
        migrations.RenameField(
            model_name='pub',
            old_name='craft_Beer',
            new_name='craft_beer',
        ),
        migrations.RenameField(
            model_name='pub',
            old_name='date_created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='pub',
            old_name='dog_Friendly',
            new_name='dog_friendly',
        ),
        migrations.RenameField(
            model_name='pub',
            old_name='name',
            new_name='pub_name',
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default=0)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('closed', models.BooleanField(default=False)),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='pubs.pub')),
            ],
            options={
                'unique_together': {('pub', 'day')},
            },
        ),
    ]
