# Generated by Django 4.2.21 on 2025-06-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0004_rename_post_comment_pub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default=0)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('closed', models.BooleanField(default=False)),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='pubs.pub')),
            ],
            options={
                'unique_together': {('pub', 'day')},
            },
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
    ]
