# Generated by Django 4.2.21 on 2025-06-17 08:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0004_pub_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
