# Generated by Django 4.2.21 on 2025-06-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0006_alter_comment_options_alter_pub_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pub',
            old_name='pub_name',
            new_name='name',
        ),
    ]
