# Generated by Django 4.2.21 on 2025-06-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0006_pub_fri_opening_pub_mon_opening_pub_sat_opening_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpeningHour',
        ),
    ]
