# Generated by Django 4.2.21 on 2025-06-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0007_delete_openinghour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='excerpt',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
