# Generated by Django 4.2.21 on 2025-06-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0008_alter_pub_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
