# Generated by Django 4.2.21 on 2025-06-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
        migrations.RemoveField(
            model_name='about',
            name='author',
        ),
        migrations.RemoveField(
            model_name='about',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='about',
            name='slug',
        ),
        migrations.AddField(
            model_name='about',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
